name: Publish Docker image
on:
  pull_request:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nandawtek/martian-robots:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.REGISTRY_TOKEN }}
